version: '2'
services:
  app:
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./app:/usr/local/etc/app
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: exapp
      MYSQL_DATABASE: exapp_db
      MYSQL_USER: exapp_user
      MYSQL_PASSWORD: exapp

