version: '3'
services:
  app:
    build: ./app
    ports:
      - '3000:3000'
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: exapp
      MYSQL_DATABASE: exapp_db
      MYSQL_USER: exapp_user
      MYSQL_PASSWORD: exapp
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
